name: Installation Test

on: push

# inputs:

# example:
#   test_scope: tests/basic/ptf.js,tests/basic/conv.js
#   target_server: marist1,marist2,marist3

# example: >>> bundle tests/installation/src/__tests__/extended/security-systems/ptf/
#   test_scope: tests/basic/install-ptf.js
#   target_server: marist1,marist2,marist3

# example:
#   test_scope: tests/extended/node-versions/
#         v8,v12,v14
#   target_server: marist1,marist2,marist3

jobs:
  # setup-matrix:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Setup matrix
  #       id: setup-matrix
  #       run: |
  #         echo ::set-output name=test-matrix::{\"include\":[{\"test\":\"file1.js\",\"server\":\"marist1\"},{\"test\":\"file2.js\",\"server\":\"marist1\"},{\"test\":\"file1.js\",\"server\":\"marist2\"},{\"test\":\"file1.js\",\"server\":\"marist2\"}]}
  #   outputs:
  #     test-matrix: ${{ steps.setup-matrix.outputs.test-matrix }}

  # snyk:
  #   runs-on: ubuntu-latest
  #   needs: setup-matrix
  #   strategy:
  #     matrix: ${{ fromJson(needs.setup-matrix.outputs.test-matrix) }}
  #   environment: ${{ matrix.server }}
  #   steps:
  #   - uses: actions/checkout@v2

  #   - name: Run test
  #     env:
  #       SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
  #     run: "echo test=${{ matrix.test }}"

  job1:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - id: set-matrix
      run: echo "::set-output name=matrix::{\"include\":[{\"test\":\"foo\",\"env\":\"marist1\"},{\"test\":\"bar\",\"env\":\"marist1\"},{\"test\":\"foo\",\"env\":\"marist2\"},{\"test\":\"bar\",\"env\":\"marist2\"}]}"
  job2:
    needs: job1
    runs-on: ubuntu-latest
    environment: ${{ matrix.env }}
    strategy:
      matrix: ${{fromJson(needs.job1.outputs.matrix)}}
    steps:
    - name: lock server
      uses: zowe-actions/acquire-lock
      with:
        server: ${{ matrix.env }}

    - run: |
        echo test=${{ matrix.test }}
        echo ${{ env.SSH_USERNAME }} | sed 's/.\{1\}/&__/g'
      env:
        SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
