name: Installation Test

on: push

# inputs:
#   target_server: marist1,marist2

jobs:
  setup-matrix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup matrix
        id: setup-matrix
        run: |
          echo ::set-output name=test-matrix::{\"test\":[\"file1.js\",\"file2.js\"],\"server\":[\"marist1\",\"marist2\"]}
    outputs:
      test-matrix: ${{ steps.setup-matrix.outputs.test-matrix }}

  snyk:
    runs-on: ubuntu-latest
    needs: setup-matrix
    strategy:
      matrix: ${{ fromJson(needs.setup-matrix.outputs.test-matrix) }}
    environment: ${{ matrix.server }}
    steps:
    - uses: actions/checkout@v2

    - name: Run test
      env:
        SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
      run: "echo test=${{ matrix.test }}"
