name: Zowe Nightly Pipeline
on:
  push: 
    branches: 
      - users/tom/nightly2ma5ter

jobs:
  call-build-workflow:
    uses: zowe/zowe-install-packaging/.github/workflows/build-packaging.yml@staging
    with:
      BUILD_SMPE: true
      BUILD_PSIANDSMPE: false
      BUILD_DOCKER: true
      BUILD_DOCKER_SOURCES: false
      BUILD_KUBERNETES: true
      KEEP_TEMP_PAX_FOLDER: false
    secrets:
      JF_ARTIFACTORY_TOKEN: ${{ secrets.JF_ARTIFACTORY_TOKEN }}
      SSH_MARIST_USERNAME: ${{ secrets.SSH_MARIST_USERNAME }}
      SSH_MARIST_RACF_PASSWORD: ${{ secrets.SSH_MARIST_RACF_PASSWORD }}
      ZLINUX_SSH_KEY: ${{ secrets.ZLINUX_SSH_KEY }}
      ZLINUX_HOST: ${{ secrets.ZLINUX_HOST }}
      ZLINUX_SSH_USER: ${{ secrets.ZLINUX_SSH_USER }}
      ZLINUX_SSH_PASSPHRASE: ${{ secrets.ZLINUX_SSH_PASSPHRASE }}
      DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

  call-test-workflow:
    needs: call-build-workflow
    uses: zowe/zowe-install-packaging/.github/workflows/cicd-test.yml@staging
    with: 
      test-file-server: basic/install.ts(zzow02,zzow03,zzow04);basic/install-ptf.ts(zzow02,zzow03,zzow04);basic/install-docker.ts(zzow04)
    secrets:
      JF_ARTIFACTORY_TOKEN: ${{ secrets.JF_ARTIFACTORY_TOKEN }}