name: Zowe Nightly Pipeline
on:
  push: 
    branches: 
      - users/tom/nightly2ma5ter

jobs:
  # call-build-workflow:
  #   uses: zowe/zowe-install-packaging/.github/workflows/build-packaging.yml@users/tom/nightly2ma5ter
  #   with:
  #     NIGHTLY: true
  #     BUILD_SMPE: true
  #     BUILD_PSIANDSMPE: false
  #     BUILD_DOCKER: true
  #     BUILD_DOCKER_SOURCES: false
  #     BUILD_KUBERNETES: true
  #     KEEP_TEMP_PAX_FOLDER: false
  #   secrets:
  #     JF_ARTIFACTORY_TOKEN: ${{ secrets.JF_ARTIFACTORY_TOKEN }}
  #     SSH_MARIST_USERNAME: ${{ secrets.SSH_MARIST_USERNAME }}
  #     SSH_MARIST_RACF_PASSWORD: ${{ secrets.SSH_MARIST_RACF_PASSWORD }}
  #     ZLINUX_SSH_KEY: ${{ secrets.ZLINUX_SSH_KEY }}
  #     ZLINUX_HOST: ${{ secrets.ZLINUX_HOST }}
  #     ZLINUX_SSH_USER: ${{ secrets.ZLINUX_SSH_USER }}
  #     ZLINUX_SSH_PASSPHRASE: ${{ secrets.ZLINUX_SSH_PASSPHRASE }}
  #     DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
  #     DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

  call-test-workflow:
    # needs: call-build-workflow
    uses: zowe/zowe-install-packaging/.github/workflows/cicd-test.yml@users/tom/nightly2ma5ter
    with: 
      NIGHTLY: true
      test-file-server: basic/install.ts(zzow02,zzow03,zzow04);basic/install-ptf.ts(zzow02,zzow03,zzow04);basic/install-docker.ts(zzow04)
    secrets:
      JF_ARTIFACTORY_TOKEN: ${{ secrets.JF_ARTIFACTORY_TOKEN }}
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_PORT: ${{ secrets.SSH_PORT }}
      SSH_USER: ${{ secrets.SSH_USER }}
      SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
    # Above secrets exists in the environment, doing secrets here to mitigate a problem of reusable workflows where environment secret can
    #   not be passed in properly
    # More info: https://github.community/t/reusable-workflows-secrets-and-environments/203695/23
    # it was a bit weird to pass in above secrets, hope Github team can improve on this

  